import { HOTEL_DEMO_ASSETS } from "../../hotel/data/demoAssets";
import type { Experience, Offer, Page, Review, Room, Settings } from "./types";

export type LocalCmsData = {
  settings: Settings;
  rooms: Room[];
  offers: Offer[];
  experiences: Experience[];
  reviews: Review[];
  pages: Page[];
};

const updated_at = "2026-06-04";
const published = { status: "published", updated_at };

export const localCmsData: LocalCmsData = {
  settings: {
    ...published,
    hotel_slug: "oria-house-barcelona",
    hotel_name_en: "Oria House Barcelona",
    hotel_name_es: "Oria House Barcelona",
    address_en: "Carrer de Mallorca 259, Eixample, Barcelona",
    address_es: "Carrer de Mallorca 259, Eixample, Barcelona",
    coords_lat: "41.3926",
    coords_lng: "2.1649",
    phone: "+34 930 000 000",
    whatsapp: "+34 630 000 000",
    email: "reservations@oria-house.example",
    booking_provider: "concept",
    booking_url: "/en/contact/",
    languages: "en|es",
    brand_theme: "barcelona-boutique",
    social_instagram: "https://www.instagram.com/",
    social_google_maps: "https://maps.google.com/?q=Barcelona",
    hero_image: HOTEL_DEMO_ASSETS.homeHero,
  },
  rooms: [
    {
      ...published,
      id: "room-01",
      sort_order: "1",
      slug: "studio-courtyard",
      name_en: "Studio Courtyard",
      name_es: "Studio patio",
      short_en: "A quiet studio facing the inner courtyard.",
      short_es: "Un estudio tranquilo orientado al patio interior.",
      description_en:
        "A soft base for short city stays, framed by morning light, warm materials and a calm courtyard rhythm.",
      description_es:
        "Una base suave para estancias cortas, con luz de manana, materiales calidos y ritmo tranquilo de patio.",
      price_from: "From EUR 220",
      size_sqm: "28",
      guests: "2",
      beds_en: "Queen bed",
      beds_es: "Cama queen",
      amenities_en: "Courtyard view|Rain shower|Desk|Ritual bath set",
      amenities_es: "Vista al patio|Ducha efecto lluvia|Escritorio|Set de bano ritual",
      highlights_en: "Quiet inner view|Best for weekend arrivals|Direct booking clarity",
      highlights_es: "Vista interior tranquila|Ideal para fines de semana|Reserva directa clara",
      cover_image: HOTEL_DEMO_ASSETS.roomStudioCourtyard,
      gallery_images: HOTEL_DEMO_ASSETS.roomStudioCourtyard,
    },
    {
      ...published,
      id: "room-02",
      sort_order: "2",
      slug: "studio-skyline",
      name_en: "Studio Skyline",
      name_es: "Studio skyline",
      short_en: "A compact city-facing studio with upper-floor light.",
      short_es: "Un estudio compacto con luz de planta alta y vista urbana.",
      description_en:
        "Designed for guests who want a sharper city signal: clean lines, open light and a practical stay rhythm.",
      description_es:
        "Pensado para quienes buscan una senal urbana mas clara: lineas limpias, luz abierta y ritmo practico.",
      price_from: "From EUR 240",
      size_sqm: "30",
      guests: "2",
      beds_en: "Queen bed",
      beds_es: "Cama queen",
      amenities_en: "City view|Desk|Blackout curtains|Walk-in shower",
      amenities_es: "Vista urbana|Escritorio|Cortinas blackout|Ducha amplia",
      highlights_en: "Upper-floor light|Compact planning|Easy direct booking",
      highlights_es: "Luz de planta alta|Distribucion compacta|Reserva directa sencilla",
      cover_image: HOTEL_DEMO_ASSETS.roomStudioSkyline,
      gallery_images: HOTEL_DEMO_ASSETS.roomStudioSkyline,
    },
    {
      ...published,
      id: "room-03",
      sort_order: "3",
      slug: "superior-balc",
      name_en: "Superior Balcony",
      name_es: "Superior balcon",
      short_en: "A balcony room for slow morning air.",
      short_es: "Una habitacion con balcon para mananas pausadas.",
      description_en:
        "A balanced room with private outdoor pause points, soft textiles and a direct line to the neighborhood.",
      description_es:
        "Una habitacion equilibrada con pausa exterior privada, textiles suaves y conexion directa con el barrio.",
      price_from: "From EUR 265",
      size_sqm: "32",
      guests: "2",
      beds_en: "Queen bed",
      beds_es: "Cama queen",
      amenities_en: "Balcony|Tea set|Desk|Rain shower",
      amenities_es: "Balcon|Set de te|Escritorio|Ducha efecto lluvia",
      highlights_en: "Private balcony|Morning rituals|Soft street connection",
      highlights_es: "Balcon privado|Rituales de manana|Conexion suave con la calle",
      cover_image: HOTEL_DEMO_ASSETS.roomSuperiorBalcony,
      gallery_images: HOTEL_DEMO_ASSETS.roomSuperiorBalcony,
    },
    {
      ...published,
      id: "room-04",
      sort_order: "4",
      slug: "deluxe-corner",
      name_en: "Deluxe Corner",
      name_es: "Deluxe esquina",
      short_en: "Extra light, angled views and more room to settle.",
      short_es: "Mas luz, vistas en angulo y espacio para instalarse.",
      description_en:
        "A corner room with wider visual range, layered seating and enough space for longer Barcelona days.",
      description_es:
        "Una habitacion de esquina con mayor rango visual, zona de estar y espacio para dias largos en Barcelona.",
      price_from: "From EUR 295",
      size_sqm: "36",
      guests: "2",
      beds_en: "King bed",
      beds_es: "Cama king",
      amenities_en: "Corner view|Lounge chair|Desk|Bath amenities",
      amenities_es: "Vista de esquina|Butaca|Escritorio|Amenities de bano",
      highlights_en: "More light|Longer-stay comfort|Strong visual identity",
      highlights_es: "Mas luz|Comodidad para estancias largas|Identidad visual clara",
      cover_image: HOTEL_DEMO_ASSETS.roomDeluxeCorner,
      gallery_images: HOTEL_DEMO_ASSETS.roomDeluxeCorner,
    },
    {
      ...published,
      id: "room-05",
      sort_order: "5",
      slug: "deluxe-terrace",
      name_en: "Deluxe Terrace",
      name_es: "Deluxe terraza",
      short_en: "A terrace room built around private outdoor time.",
      short_es: "Una habitacion con terraza pensada para tiempo exterior privado.",
      description_en:
        "The room opens into a private terrace moment for coffee, dusk returns and quiet planning before dinner.",
      description_es:
        "La habitacion se abre a una terraza privada para cafe, regreso al atardecer y planes tranquilos antes de cenar.",
      price_from: "From EUR 340",
      size_sqm: "38",
      guests: "2",
      beds_en: "King bed",
      beds_es: "Cama king",
      amenities_en: "Private terrace|Outdoor seating|Minibar|Rain shower",
      amenities_es: "Terraza privada|Zona exterior|Minibar|Ducha efecto lluvia",
      highlights_en: "Private terrace|Golden-hour return|Best direct rate",
      highlights_es: "Terraza privada|Regreso a la hora dorada|Mejor tarifa directa",
      cover_image: HOTEL_DEMO_ASSETS.roomDeluxeTerrace,
      gallery_images: HOTEL_DEMO_ASSETS.roomDeluxeTerrace,
    },
    {
      ...published,
      id: "room-06",
      sort_order: "6",
      slug: "junior-suite",
      name_en: "Junior Suite",
      name_es: "Junior suite",
      short_en: "A larger room with a proper sitting rhythm.",
      short_es: "Una habitacion mas amplia con ritmo de estar propio.",
      description_en:
        "Built for guests who want the room to carry part of the stay: reading, planning and slow transitions.",
      description_es:
        "Pensada para quienes quieren que la habitacion sea parte de la estancia: lectura, planes y transiciones lentas.",
      price_from: "From EUR 390",
      size_sqm: "44",
      guests: "3",
      beds_en: "King bed and sofa",
      beds_es: "Cama king y sofa",
      amenities_en: "Sitting area|Bathrobe|Desk|Expanded minibar",
      amenities_es: "Zona de estar|Albornoz|Escritorio|Minibar ampliado",
      highlights_en: "Suite rhythm|Extra seating|Best for longer stays",
      highlights_es: "Ritmo de suite|Zona de estar extra|Ideal para estancias largas",
      cover_image: HOTEL_DEMO_ASSETS.roomJuniorSuite,
      gallery_images: HOTEL_DEMO_ASSETS.roomJuniorSuite,
    },
    {
      ...published,
      id: "room-07",
      sort_order: "7",
      slug: "suite-eixample",
      name_en: "Suite Eixample",
      name_es: "Suite Eixample",
      short_en: "A suite with calm scale and neighborhood presence.",
      short_es: "Una suite con escala tranquila y presencia de barrio.",
      description_en:
        "A generous suite for arrivals that need more privacy, more storage and a more cinematic room presence.",
      description_es:
        "Una suite generosa para llegadas que necesitan mas privacidad, mas almacenaje y una presencia mas cinematica.",
      price_from: "From EUR 460",
      size_sqm: "52",
      guests: "3",
      beds_en: "King bed and lounge",
      beds_es: "Cama king y salon",
      amenities_en: "Separate lounge|Large bathroom|Coffee set|Bathrobe",
      amenities_es: "Salon separado|Bano amplio|Set de cafe|Albornoz",
      highlights_en: "More privacy|Suite scale|Local route planning",
      highlights_es: "Mas privacidad|Escala de suite|Planificacion de rutas locales",
      cover_image: HOTEL_DEMO_ASSETS.roomSuiteExample,
      gallery_images: HOTEL_DEMO_ASSETS.roomSuiteExample,
    },
    {
      ...published,
      id: "room-08",
      sort_order: "8",
      slug: "suite-terrace",
      name_en: "Suite Terrace",
      name_es: "Suite terraza",
      short_en: "Suite scale with a private outdoor edge.",
      short_es: "Escala de suite con un borde exterior privado.",
      description_en:
        "A composed suite for guests who want terrace air, larger interiors and a slower evening return.",
      description_es:
        "Una suite compuesta para quienes buscan aire de terraza, interiores mas amplios y regreso nocturno pausado.",
      price_from: "From EUR 520",
      size_sqm: "56",
      guests: "3",
      beds_en: "King bed and lounge",
      beds_es: "Cama king y salon",
      amenities_en: "Private terrace|Lounge|Coffee set|Large bathroom",
      amenities_es: "Terraza privada|Salon|Set de cafe|Bano amplio",
      highlights_en: "Terrace air|Suite comfort|Evening return",
      highlights_es: "Aire de terraza|Comodidad de suite|Regreso al atardecer",
      cover_image: HOTEL_DEMO_ASSETS.roomDeluxeTerrace,
      gallery_images: HOTEL_DEMO_ASSETS.roomDeluxeTerrace,
    },
    {
      ...published,
      id: "room-09",
      sort_order: "9",
      slug: "penthouse",
      name_en: "Penthouse",
      name_es: "Penthouse",
      short_en: "The top-floor stay with the strongest sense of occasion.",
      short_es: "La estancia en planta alta con mayor sentido de ocasion.",
      description_en:
        "A high-room experience for private celebrations, calm mornings and a more deliberate Barcelona stay.",
      description_es:
        "Una experiencia en planta alta para celebraciones privadas, mananas tranquilas y una estancia mas deliberada.",
      price_from: "From EUR 690",
      size_sqm: "68",
      guests: "3",
      beds_en: "King bed and lounge",
      beds_es: "Cama king y salon",
      amenities_en: "Top floor|Terrace|Large lounge|Priority arrival",
      amenities_es: "Planta alta|Terraza|Salon amplio|Llegada prioritaria",
      highlights_en: "Highest privacy|Occasion stay|Priority direct booking",
      highlights_es: "Maxima privacidad|Estancia de ocasion|Reserva directa prioritaria",
      cover_image: HOTEL_DEMO_ASSETS.roomPenthouse,
      gallery_images: HOTEL_DEMO_ASSETS.roomPenthouse,
    },
    {
      ...published,
      id: "room-10",
      sort_order: "10",
      slug: "family-suite",
      name_en: "Family Suite",
      name_es: "Suite familiar",
      short_en: "A practical suite for shared city time.",
      short_es: "Una suite practica para tiempo compartido en la ciudad.",
      description_en:
        "Flexible sleeping, generous storage and a calmer base for families moving through Barcelona together.",
      description_es:
        "Descanso flexible, almacenaje generoso y una base tranquila para familias que recorren Barcelona juntas.",
      price_from: "From EUR 480",
      size_sqm: "58",
      guests: "4",
      beds_en: "King bed and sofa bed",
      beds_es: "Cama king y sofa cama",
      amenities_en: "Family layout|Sofa bed|Large bathroom|Extra storage",
      amenities_es: "Distribucion familiar|Sofa cama|Bano amplio|Almacenaje extra",
      highlights_en: "Flexible sleeping|Family planning|More storage",
      highlights_es: "Descanso flexible|Plan familiar|Mas almacenaje",
      cover_image: HOTEL_DEMO_ASSETS.roomFamilySuite,
      gallery_images: HOTEL_DEMO_ASSETS.roomFamilySuite,
    },
    {
      ...published,
      id: "room-11",
      sort_order: "11",
      slug: "accessible",
      name_en: "Accessible Room",
      name_es: "Habitacion accesible",
      short_en: "A calmer accessible room with clear movement paths.",
      short_es: "Una habitacion accesible y tranquila con recorridos claros.",
      description_en:
        "Designed for easier movement, direct planning and the same soft material language as the wider house.",
      description_es:
        "Disenada para facilitar el movimiento, planificacion directa y el mismo lenguaje material suave de la casa.",
      price_from: "From EUR 250",
      size_sqm: "34",
      guests: "2",
      beds_en: "Queen bed",
      beds_es: "Cama queen",
      amenities_en: "Accessible layout|Walk-in shower|Clear circulation|Desk",
      amenities_es: "Distribucion accesible|Ducha amplia|Circulacion clara|Escritorio",
      highlights_en: "Clear movement|Direct arrival planning|Quiet room",
      highlights_es: "Movimiento claro|Planificacion directa de llegada|Habitacion tranquila",
      cover_image: HOTEL_DEMO_ASSETS.roomAccessibleRoom,
      gallery_images: HOTEL_DEMO_ASSETS.roomAccessibleRoom,
    },
    {
      ...published,
      id: "room-12",
      sort_order: "12",
      slug: "courtyard-suite",
      name_en: "Courtyard Suite",
      name_es: "Suite patio",
      short_en: "A suite turned inward toward quiet architecture.",
      short_es: "Una suite orientada hacia una arquitectura tranquila.",
      description_en:
        "A deeper, quieter suite built around inner light, textured walls and a slower private room rhythm.",
      description_es:
        "Una suite mas profunda y tranquila, construida alrededor de luz interior, textura y ritmo privado.",
      price_from: "From EUR 430",
      size_sqm: "50",
      guests: "3",
      beds_en: "King bed and lounge",
      beds_es: "Cama king y salon",
      amenities_en: "Courtyard view|Lounge|Coffee set|Rain shower",
      amenities_es: "Vista al patio|Salon|Set de cafe|Ducha efecto lluvia",
      highlights_en: "Inner quiet|Architectural detail|Suite comfort",
      highlights_es: "Tranquilidad interior|Detalle arquitectonico|Comodidad de suite",
      cover_image: HOTEL_DEMO_ASSETS.roomCourtyardSuite,
      gallery_images: HOTEL_DEMO_ASSETS.roomCourtyardSuite,
    },
  ],
  offers: [
    {
      ...published,
      id: "offer-01",
      sort_order: "1",
      slug: "stay-3-pay-2",
      title_en: "Stay 3, Pay 2",
      title_es: "3 noches, paga 2",
      period_en: "Selected weekdays and shoulder-season arrivals",
      period_es: "Dias seleccionados y llegadas de temporada media",
      included_en: "Third night included|Direct booking support|Flexible arrival note",
      included_es: "Tercera noche incluida|Soporte de reserva directa|Nota de llegada flexible",
      terms_en: "Subject to availability|Limited rooms|Direct bookings only",
      terms_es: "Sujeto a disponibilidad|Habitaciones limitadas|Solo reservas directas",
      cta_type: "booking",
      cover_image: HOTEL_DEMO_ASSETS.offerStay3Pay2,
      gallery_images: HOTEL_DEMO_ASSETS.offerStay3Pay2,
    },
    {
      ...published,
      id: "offer-02",
      sort_order: "2",
      slug: "romance-weekend",
      title_en: "Romance Weekend",
      title_es: "Fin de semana romantico",
      period_en: "Friday and Saturday arrivals",
      period_es: "Llegadas viernes y sabado",
      included_en: "Late check-out|Welcome detail|Breakfast rhythm|Room preference note",
      included_es: "Late check-out|Detalle de bienvenida|Ritmo de desayuno|Preferencia de habitacion",
      terms_en: "Two-night minimum|Direct bookings only|Limited upgrades",
      terms_es: "Minimo dos noches|Solo reservas directas|Upgrades limitados",
      cta_type: "booking",
      cover_image: HOTEL_DEMO_ASSETS.offerRomanceWeekend,
      gallery_images: HOTEL_DEMO_ASSETS.offerRomanceWeekend,
    },
    {
      ...published,
      id: "offer-03",
      sort_order: "3",
      slug: "culture-pass",
      title_en: "Culture Pass",
      title_es: "Pase cultural",
      period_en: "Museum mornings and architectural weekends",
      period_es: "Mananas de museo y fines de semana arquitectonicos",
      included_en: "Local route note|Early breakfast window|Concierge planning|Direct rate",
      included_es: "Nota de ruta local|Ventana de desayuno temprano|Planificacion concierge|Tarifa directa",
      terms_en: "Subject to route availability|Direct bookings only",
      terms_es: "Sujeto a disponibilidad de ruta|Solo reservas directas",
      cta_type: "contact",
      cover_image: HOTEL_DEMO_ASSETS.offerCulturePass,
      gallery_images: HOTEL_DEMO_ASSETS.offerCulturePass,
    },
  ],
  experiences: [
    {
      ...published,
      id: "experience-01",
      sort_order: "1",
      slug: "rooftop-sunset",
      category: "event",
      title_en: "Rooftop Sunset",
      title_es: "Atardecer en terraza",
      description_en:
        "A slow rooftop hour shaped around low light, city silhouettes and an easy return to the room.",
      description_es:
        "Una hora pausada en terraza con luz baja, siluetas urbanas y regreso facil a la habitacion.",
      cta_type: "booking",
      cover_image: HOTEL_DEMO_ASSETS.experienceRooftopSunset,
      gallery_images: HOTEL_DEMO_ASSETS.experienceRooftopSunset,
    },
    {
      ...published,
      id: "experience-02",
      sort_order: "2",
      slug: "spa-ritual",
      category: "spa",
      title_en: "Spa Ritual",
      title_es: "Ritual spa",
      description_en:
        "A compact wellness ritual for arrivals, recovery days and quiet transitions between city routes.",
      description_es:
        "Un ritual wellness compacto para llegadas, dias de recuperacion y transiciones tranquilas.",
      cta_type: "booking",
      cover_image: HOTEL_DEMO_ASSETS.experienceSpaRitual,
      gallery_images: HOTEL_DEMO_ASSETS.experienceSpaRitual,
    },
    {
      ...published,
      id: "experience-03",
      sort_order: "3",
      slug: "signature-breakfast",
      category: "breakfast",
      title_en: "Signature Breakfast",
      title_es: "Desayuno signature",
      description_en:
        "A softer breakfast window for guests who want the first hour of the day to feel intentional.",
      description_es:
        "Una ventana de desayuno mas suave para quienes quieren que la primera hora sea intencional.",
      cta_type: "booking",
      cover_image: HOTEL_DEMO_ASSETS.experienceSignatureBreakfast,
      gallery_images: HOTEL_DEMO_ASSETS.experienceSignatureBreakfast,
    },
    {
      ...published,
      id: "experience-04",
      sort_order: "4",
      slug: "wine-pairing",
      category: "dining",
      title_en: "Wine Pairing",
      title_es: "Maridaje de vinos",
      description_en:
        "A dining-led evening with local bottles, small plates and an easy path back upstairs.",
      description_es:
        "Una noche gastronomica con vinos locales, pequenos platos y regreso facil a la habitacion.",
      cta_type: "contact",
      cover_image: HOTEL_DEMO_ASSETS.galleryDiningEvening,
      gallery_images: HOTEL_DEMO_ASSETS.galleryDiningEvening,
    },
    {
      ...published,
      id: "experience-05",
      sort_order: "5",
      slug: "gaudi-morning",
      category: "tour",
      title_en: "Gaudi Morning",
      title_es: "Manana Gaudi",
      description_en:
        "An early route concept for architecture, quieter streets and a cleaner start before the city fills.",
      description_es:
        "Una ruta temprana de arquitectura, calles mas tranquilas y comienzo limpio antes de que la ciudad se llene.",
      cta_type: "contact",
      cover_image: HOTEL_DEMO_ASSETS.experienceGaudiMorning,
      gallery_images: HOTEL_DEMO_ASSETS.experienceGaudiMorning,
    },
    {
      ...published,
      id: "experience-06",
      sort_order: "6",
      slug: "beachday-kit",
      category: "culture",
      title_en: "Beach Day Kit",
      title_es: "Kit dia de playa",
      description_en:
        "A light planning layer for a beach day: timing, towels, route note and return rhythm.",
      description_es:
        "Una capa ligera para un dia de playa: horarios, toallas, ruta y ritmo de regreso.",
      cta_type: "booking",
      cover_image: HOTEL_DEMO_ASSETS.experienceBeachDayKit,
      gallery_images: HOTEL_DEMO_ASSETS.experienceBeachDayKit,
    },
    {
      ...published,
      id: "experience-07",
      sort_order: "7",
      slug: "design-book-shelf",
      category: "culture",
      title_en: "Design Book Shelf",
      title_es: "Biblioteca de diseno",
      description_en:
        "A quiet in-house pause built around design books, coffee and slower afternoon light.",
      description_es:
        "Una pausa tranquila en la casa con libros de diseno, cafe y luz lenta de tarde.",
      cta_type: "contact",
      cover_image: HOTEL_DEMO_ASSETS.detailDeskMorning,
      gallery_images: HOTEL_DEMO_ASSETS.detailDeskMorning,
    },
    {
      ...published,
      id: "experience-08",
      sort_order: "8",
      slug: "private-photo-walk",
      category: "tour",
      title_en: "Private Photo Walk",
      title_es: "Paseo fotografico privado",
      description_en:
        "A private route for guests who want architecture, light and personal images without a rushed schedule.",
      description_es:
        "Una ruta privada para quienes buscan arquitectura, luz e imagenes personales sin agenda acelerada.",
      cta_type: "contact",
      cover_image: HOTEL_DEMO_ASSETS.experiencePrivatePhotoWalk,
      gallery_images: HOTEL_DEMO_ASSETS.experiencePrivatePhotoWalk,
    },
  ],
  reviews: [
    {
      ...published,
      id: "review-01",
      sort_order: "1",
      source: "Concept review",
      rating: "4.9",
      quote_en: "The room felt quiet without losing the city.",
      quote_es: "La habitacion se sentia tranquila sin perder la ciudad.",
      author_en: "Weekend guest",
      author_es: "Huesped de fin de semana",
    },
    {
      ...published,
      id: "review-02",
      sort_order: "2",
      source: "Concept review",
      rating: "4.8",
      quote_en: "The direct booking flow made the stay feel considered from the start.",
      quote_es: "La reserva directa hizo que la estancia se sintiera cuidada desde el inicio.",
      author_en: "Direct booking guest",
      author_es: "Huesped de reserva directa",
    },
    {
      ...published,
      id: "review-03",
      sort_order: "3",
      source: "Concept review",
      rating: "4.9",
      quote_en: "A calm base with enough design detail to remember.",
      quote_es: "Una base tranquila con suficiente detalle de diseno para recordar.",
      author_en: "City break guest",
      author_es: "Huesped de escapada urbana",
    },
  ],
  pages: [],
};
